### ISSUE TITLE
Reconnection token failed

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry/noaa#14]
Hi,

As you know we provide an authToken in order to connect to the firehose.
If a problem occur we try to reconnect, but if the reconnection happen after the token get expire we could not reconnect.

Can be nice if the noaa lib could manage the auth and manage the token life.

@wfernandes

**Comment by shinji62** [comment]
Seems this issue imply refresh token too https://github.com/cloudfoundry/noaa/issues/18
I pretty sure we can do something better to avoid this refresh problem.

**Comment by wfernandes** [comment]
@shinji62 We are currently looking into the best way to refresh the token within noaa.

**Comment by claudio-benfatto** [comment]
Hello @wfernandes ,

we are currently experiencing a similar problem while using a nozzle, which eventually fails to reconnect with the following error message: 

> "Unauthorized error: You are not authorized. Error: Invalid authorization"

I see some code related to the token refresh issue committed here: `consumer/token_refresher.go` , 
Is this a working example I can refer to: `samples/token_refresher/main.go`?

I'm really looking forward to having the problem fixed, in the meanwhile thank you for your work.

Claudio

**Comment by wfernandes** [comment]
@claudio-benfatto The sample is a great start at implementing the token-refresh logic. 

We've left it up to the user to determine how to refresh the auth token as long as y'all implement the interface.

**Comment by shinji62** [comment]
I will implement in firehose-to-syslog soon. 

thanks @wfernandes

**Comment by claudio-benfatto** [comment]
Thank you @wfernandes I had reached the same conclusion after examining the code. Yet I was wondering why the issue was still open.

Very well then :+1:
