### ISSUE TITLE
include timstamp when getting container metrics

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry/noaa#19]
when calling 'noaa.ContainerMetrics(appId, token)', the timestamp is lost.  We will need to know when the metrics are collected. Otherwise we will not know whether it is up-to-date or not. 

If we delete some instances of an app, we still get the container metrics of the instances for the following several minutes.  With the timestamp info, we will at least know when the last metrics were collected.

**Comment by wfernandes** [comment]
@boyang9527 Thanks for submitting this issue. Will work with the PM to prioritize this story in the upcoming iterations.
