### ISSUE TITLE
Feature request: accept https_proxy

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/noaa#30]
The cf CLI relies on noaa to talk to loggregator.
It appears `cf logs myapp` works when behind a proxy when http_proxy is set, not with https_proxy.
As https_proxy seems to be the standard environment variable to use to specify an http proxy to an https endpoint, in cf CLI help and documentation we suggest that (although by virtue of being implemented in golang it supports both, in lower and in upper case).

Can noaa also be made to accept https_proxy?

**Comment by enocom** [comment]
Resolved by b4a216f4c6b05ee90589f14ecab4570d45eb8160.

**Comment by ahevenor** [comment]
@dkoper - this should be good now. Below is how I tested this.

__Acceptance Notes__
1. Setup a local proxy
1. Checked out a previous version of the noaa client before `842bea`
1. Built the firehose sample with `https_proxy='localhost:8080' go run main.go`
1. The proxy did not connect
1. Built the firehose sample with 
`http_proxy='localhost:8080' go run main.go`
1. Saw the connection made to the proxy
1. Checked out latest version of noaa client
1. Saw the connection made to the proxy
1. Built the firehose sample with 
`http_proxy='localhost:8080' go run main.go`
1. Saw the connection made to the proxy

**Comment by dkoper** [comment]
Thanks!
