### ISSUE TITLE
Allow more flexible recent logs URL structure

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/noaa#33]
We are thinking of submitting a PR on noaa and would like to discuss the proposed change prior to doing that.

We have a service broker which needs to surface a special logs endpoint along the lines of a doppler endpoint, but we would like to get away from the hardcoded URL structure that noaa presumes for recent logs endpoints. The proposed change maintains the current noaa behaviour as default but allows the caller to specify their own function for constructing the recent logs endpoint URL from its constituents. The draft code, and tests, are here: https://github.com/glyn/noaa/commit/07aabc4509d8ea37a81f596d5918dc5094e5b90f

If this is acceptable, then -- after more testing -- we'll submit a PR. Any feedback gratefully received.

**Comment by jasonkeene** [comment]
You can make `func(trafficControllerUrl *url.URL, appGuid string, endpoint string) string` a named type just to make passing it as an argument more readable. For instance:

```go
type RecentPathBuilder func(trafficControllerUrl *url.URL, appGuid string, endpoint string) string
...
type Consumer struct {
...
 	 recentPathBuilder RecentPathBuilder
}
...
func (c *Consumer) SetRecentPathBuilder(b RecentPathBuilder) {
```

I am curious what your use case for this is. If you want to ping me on slack we can discuss. Either way you should submit a PR.

**Comment by glyn** [comment]
@jasonkeene Apologies for the delay in responding - just back from vacation.

Thanks for the feedback. We'll add a type definition for the func.

We will submit a PR in due course, and close this issue, when we have checked that the change is sufficient for our purposes (it's holding up well so far).

Our usecase is that we are providing an endpoint which mirrors some of the function of a doppler endpoint and we'd like to use noaa to access that endpoint instead of duplicating a lot of Go code. You should have access to [this feature narrative](https://docs.google.com/document/d/1rtlGIwA0Ndr7ghO6AyYE3I9kDMfT1IntnxMUobSG4Hg/edit#heading=h.alyoo9ovsg5p) if you want more background.

**Comment by glyn** [comment]
https://www.pivotaltracker.com/story/show/147825729 covers the raising of the PR. (@jasonkeene: please feel free to close https://www.pivotaltracker.com/story/show/146711055.)
