### ISSUE TITLE
SOCKS5 proxy support by way of setting proxy env var

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/noaa#38]
Golang 1.9 added support for SOCKS5 proxies. It works out of the box for the cf CLI, except for `cf logs`.

We figured out how to get socks5 proxy to work with `cf logs`. It requires some changes to the websocket library the loggregator team vendors (https://github.com/gorilla/websocket).

> gorilla needs to use a SOCKS dialer to establish a connection with the proxy, similar to the http transport in the second link.
> https://github.com/gorilla/websocket/blob/master/client.go#L249-L279
> https://github.com/golang/go/blob/master/src/net/http/transport.go#L1149-L1165

Please add out-of-the-box SOCKS5 proxy support?

**Comment by melnikalex** [comment]
Corresponding gorilla library issue:
https://github.com/gorilla/websocket/issues/297

They might add out-of-the box support, but if not, they also provide a workaround.

**Comment by enocom** [comment]
@melnikalex @dkoper We're thinking the proposed out-of-the-box support will be best and want to wait to pull in the change.

**Comment by melnikalex** [comment]
@enocom, That would work. We'll need that [proxy.URL](https://github.com/golang/net/blob/master/proxy/proxy.go#L71) set on the [web socket dialer](https://github.com/cloudfoundry/noaa/blob/master/consumer/consumer.go#L98) and SOCKS5 should be good to go.

**Comment by enocom** [comment]
As of [this commit](https://github.com/gorilla/websocket/commit/b89020ee79b89a7f932c5617d218fc06db382f53), gorilla/websocket supports SOCKS5 proxies. No changes in NOAA are necessary.

Closing.
