### ISSUE TITLE
http response body data is lost in error message

### ISSUE THREAD

**Issue by mattysweeps** [cloudfoundry/noaa#41]
https://github.com/cloudfoundry/noaa/blob/master/consumer/async.go#L448

`errMsg` should include the HTTP error code and response bodyerrMsg

The error returned here does not include the HTTP status code or body, making it difficult to understand why an error is occurring.

The error message becomes something like this:
```
Error dialing trafficcontroller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.my-env.my-domain.com:443).
```

Without the HTTP body or status code:
```
404 page not found
```

**Comment by MasslessParticle** [comment]
We've announced the deprecation of the TrafficController and the v1 API. Users should subscribe to the RLP or RLP-gateway using the [go-loggregator](https://github.com/cloudfoundry/go-loggregator) client
