### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry/noaa#42]
Hey everyone, is this project still supported - I believe some of the functionality like streaming logs still relies on websockets  - has this project been deprecated in favor of go-loggregator?
Thanks!

**Comment by jtuchscherer** [comment]
@scottschulthess noaa is on life-support. We will provide support and fixes for bug glaring bugs that are hard to work around. But generally, we recommend using go-loggregator from now on.

Please let me know if this does not answer your questions or you have any concerns.
