### ISSUE TITLE
building sample clients fails

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/noaa#9]
```
$ go build -o bin/firehose_sample firehose_sample/main.go
firehose_sample/main.go:8:2: cannot find package "github.com/cloudfoundry/noaa" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/cloudfoundry/noaa (from $GOROOT)
	/Users/scoen/go/src/github.com/cloudfoundry/noaa (from $GOPATH)
firehose_sample/main.go:9:2: cannot find package "github.com/cloudfoundry/sonde-go/events" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/cloudfoundry/sonde-go/events (from $GOROOT)
	/Users/scoen/go/src/github.com/cloudfoundry/sonde-go/events (from $GOPATH)
```
There are probably some path management steps necessary, however these are not documented. I don't see a `.envrc` file I am accustomed to sourcing for go projects.

**Comment by jmtuley** [comment]
1. Did you clone the repo into your GOPATH? It should live at `/Users/scoen/go/src/github.com/cloudfoundry/noaa`, judging from the output you pasted.
1. Did you use `go get` to download all dependencies? Simply navigate to the `noaa` directory and run `go get -u -v ./...` to get whatever is needed.
1. If you've satisfied both of those, then there's probably something wrong with your local configuration.

Given that you already have your GOPATH set, it may be easier just to run `go get github.com/cloudfoundry/noaa`, which will download the library to the correct place *and* grab all dependencies. Using this method, I was able to install the library and compile the sample code with the same instruction you used on a machine that had never before seen NOAA.

NOAA is a library, intended for consumption by other Go code, and so adheres to standard Go conventions (i.e. is `go get`'able). It doesn't have a `.envrc`, which is used on many other CF projects to set the GOPATH and so forth, for the same reason.

**Comment by roxtar** [comment]
To @shalako 's point, there is still benefit in updating the NOAA README to include the steps which @jmtuley listed.

**Comment by shalako** [comment]
Your README should make no assumptions about how the repo is consumed. Even within go projects in CF there are many patterns and it is very confusing. Your README should be explicit with a focus on user experience, even if it is a library and especially as you've (thankfully) gone through the trouble of providing examples that have the potential to be very useful for end-users.

**Comment by jmtuley** [comment]
Yep, @roxtar and @shalako you're both right. The README could certainly help out with that.

Before the README is updated, I'd like to ask: did those steps help, @shalako?

**Comment by dsabeti** [comment]
Hey @shalako !

We've updated the readme with better instructions for getting dependencies before building the binary. Let us know how it looks: if you don't have any more feedback we'll close the issue.

David && Nino

**Comment by shalako** [comment]
I submitted PR #10 with README changes that would provide a more painless experience for me next time.

**Comment by roxtar** [comment]
Merged PR. Closing.
